### ISSUE TITLE
Black screen on launch using HMD

### ISSUE THREAD

**Issue by stripeoll** [Microsoft/MixedReality250#3]
Periodically the project will launch into a static black screen when the application is launched from the Acer HMD.
Exiting to the Cliffside house and re-entering occasionally allows the application to launch. (this is only visible on deployment and plays fine via Unity Player)

**Comment by LanceMcCarthy** [comment]
I can confirm this is the case running MRP on Windows 10 Insider Build (16257) running the update MRP app and deployed to the HP headset.

@stripeoll Take a look at your event viewer and see if you're getting the same driver crash https://aka.ms/nvrn6c The NVIDIA driver crashes when you deploy from VS, the app sometimes launches if you do it from the desktop instead of VS or in the Cliff House

**Comment by stripeoll** [comment]
Issue resolved if you use code directly from repo rather than - https://developer.microsoft.com/en-us/windows/mixed-reality/mixed_reality_250
